CREATE TABLE Fach (
    PK_FACH VARCHAR(20) NOT NULL
);

CREATE TABLE Thema (
    PK_THEMA VARCHAR(30) NOT NULL,
    FK_FACH VARCHAR(20) NOT NULL
);

CREATE TABLE Frage(
    PK_FRAGE VARCHAR(50) NOT NULL,
    FRAGENTEXT VARCHAR(150) NOT NULL,
    FK_THEMA VARCHAR(20) NOT NULL,
    SCHWIERIGKEITSSTUFE INT NOT NULL
);

CREATE TABLE Antwort(
    PK_ANTWORT VARCHAR(30) NOT NULL,
    FK_FRAGE VARCHAR(50) NOT NULL,
    RICHTIG BOOLEAN NOT NULL
);